// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Link struct {
	LongLink  string `json:"longLink"`
	ShortLink string `json:"shortLink"`
}

type NewLink struct {
	LongLink string `json:"longLink"`
}
